### ISSUE TITLE
Mkdir destroys pre-existing directories

### ISSUE THREAD

**Issue by zerok** [ulope/pytest-sftpserver#5]
If you execute mkdir on a pre-existing directory path, that directory is replaced with a new empty one. Paramiko itself would raise an IOError on real servers. A test-case for this can be found here: https://gist.github.com/zerok/4e2d313f440436750588

**Comment by ulope** [comment]
Fixed, thanks :)

**Comment by zerok** [comment]
Thank you 😊
On 1 Jun 2015 2:23 pm, Ulrich Petri <notifications@github.com> wrote:Fixed, thanks :)
