### ISSUE TITLE
Posix pathing should be used at all times

### ISSUE THREAD

**Issue by dundeemt** [ulope/pytest-sftpserver#7]
If running tests on windows, a path that should be /home/test/file.txt is no longer accessible.  The pytest-sftpserver is putting it at \home\test\file.txt and the test results as "IOError: [Errno 2] No such file "

Python switches os.path  to posixpath or ntpath based on the running environment.  In interface.py and util.py path handling is being pulled from os.path (so when running tests in a windows envrionment os.path is using ntpath instead.) and should really always pull from posixpath.

If you import posixpath and replaced all occurrences of os.path with posixpath in those two modules, then sftpserver would also present a standard posix interface.

**Comment by dundeemt** [comment]
I've forked and setup an appveyor CI 
https://ci.appveyor.com/project/dundeemt/pytest-sftpserver/build/1.0.5

You can see the failure from unexpected pathing.

**Comment by ulope** [comment]
Thanks for noticing and fixing this and again sorry for taking so long to respond.
